-- Seed common tech skills
INSERT OR IGNORE INTO skills (name) VALUES ('Python');
INSERT OR IGNORE INTO skills (name) VALUES ('JavaScript');
INSERT OR IGNORE INTO skills (name) VALUES ('React');
INSERT OR IGNORE INTO skills (name) VALUES ('Flask');
INSERT OR IGNORE INTO skills (name) VALUES ('Node.js');
INSERT OR IGNORE INTO skills (name) VALUES ('SQL');
INSERT OR IGNORE INTO skills (name) VALUES ('HTML/CSS');
INSERT OR IGNORE INTO skills (name) VALUES ('Java');
INSERT OR IGNORE INTO skills (name) VALUES ('C++');
INSERT OR IGNORE INTO skills (name) VALUES ('Go');
INSERT OR IGNORE INTO skills (name) VALUES ('Rust');
INSERT OR IGNORE INTO skills (name) VALUES ('TypeScript');
INSERT OR IGNORE INTO skills (name) VALUES ('Swift');
INSERT OR IGNORE INTO skills (name) VALUES ('Kotlin');
INSERT OR IGNORE INTO skills (name) VALUES ('Ruby');
INSERT OR IGNORE INTO skills (name) VALUES ('PHP');
INSERT OR IGNORE INTO skills (name) VALUES ('Django');
INSERT OR IGNORE INTO skills (name) VALUES ('FastAPI');
INSERT OR IGNORE INTO skills (name) VALUES ('Vue.js');
INSERT OR IGNORE INTO skills (name) VALUES ('Angular');
INSERT OR IGNORE INTO skills (name) VALUES ('Figma');
INSERT OR IGNORE INTO skills (name) VALUES ('UI/UX Design');
INSERT OR IGNORE INTO skills (name) VALUES ('Machine Learning');
INSERT OR IGNORE INTO skills (name) VALUES ('Data Science');
INSERT OR IGNORE INTO skills (name) VALUES ('DevOps');
INSERT OR IGNORE INTO skills (name) VALUES ('Docker');
INSERT OR IGNORE INTO skills (name) VALUES ('AWS');
INSERT OR IGNORE INTO skills (name) VALUES ('Git');
INSERT OR IGNORE INTO skills (name) VALUES ('MongoDB');
INSERT OR IGNORE INTO skills (name) VALUES ('PostgreSQL');
